[package]
name = "artifacts-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "1.0"
thiserror = "2.0"
tokio = { version = "1", features = ["full"] }
